makewiki/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
  title = StringField('Title', validators=[DataRequired()])
  content = TextAreaField('Content', validators=[DataRequired()])
  submit = SubmitField('Post')

makewiki/main/routes.py
from flask import render_template, request, Blueprint
from makewiki.models import Post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
  posts = Post.query.all() #get all posts
  return render_template('home.html', posts=posts)

@main.route("/about")
def about():
  return render_template('about.html', title="About")

makewiki/posts/routes.py
from flask import (render_template, url_for, flash, redirect,
                   request, abort, Blueprint)
from flask_login import current_user, login_required
from makewiki import db
from makewiki.models import Post
from makewiki.posts.forms import PostForm


posts = Blueprint('posts', __name__)

#create a new post
@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
  form = PostForm()
  if form.validate_on_submit():
    #create a post instance
    post = Post(title=form.title.data, content=form.content.data, author=current_user)
    #add and save to db
    db.session.add(post)
    db.session.commit()

    flash('Your post has been created!', 'success')
    return redirect(url_for('main.home'))
  return render_template('create_post.html', title='New Post', 
                        form=form, legend='New Post')

#display a single post
@posts.route("/post/<int:post_id>")
def post(post_id):
  post = Post.query.get_or_404(post_id)
  return render_template('post.html', title=post.title, post=post)

#update a post
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
  post = Post.query.get_or_404(post_id)
  if post.author != current_user:
    abort(403) #return an error 'forbidden route'
  form = PostForm() #else get the post form

  #post request
  if form.validate_on_submit():
    post.title = form.title.data
    post.content = form.content.data
    db.session.commit() #commit your change
    flash('Your post has been updated', 'success')
    return redirect(url_for('posts.post', post_id=post.id))
  #get request
  elif request.method == 'GET': 
    #populate form with title and content
    form.title.data = post.title 
    form.content.data = post.content
  return render_template('create_post.html', title='Update Post', 
                        form=form, legend='Update Post')

#delete a post
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
  post = Post.query.get_or_404(post_id)
  if post.author != current_user:
    abort(403) #return an error 'forbidden route'
  #delete the post
  db.session.delete(post)
  db.session.commit()
  flash('Your post has been deleted!', 'success')
  return redirect(url_for('main.home'))

makewiki/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from makewiki import db, bcrypt
from makewiki.models import User, Post
from makewiki.users.forms import (RegistrationForm, LoginForm, 
                            RequestResetForm, ResetPasswordForm)
from makewiki.users.utils import send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = RegistrationForm()
  if form.validate_on_submit():
    #hash the pw
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    #create a new instance of the user
    user = User(username=form.username.data, email=form.email.data, password=hashed_password)
    #add the user to db and commit
    db.session.add(user)
    db.session.commit()

    flash(f'Your account has been created! You are now able to log in', 'success')
    return redirect(url_for('users.login')) #redirect to login page
  return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
      #log the user in
      login_user(user, remember=form.remember.data)
      next_page = request.args.get('next')
      #redired to home after logging in or to the next page if it exists(eg: accounts)
      return redirect(next_page) if next_page else redirect(url_for('main.home')) 
    else:
      flash('Login Unsuccessful. Please check email and password', 'danger')
  return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
  logout_user()
  return redirect(url_for('main.home')) #redired to home after logging out

@users.route("/account")
@login_required
def account():
  return render_template('account.html', title='Account')

#forgot password routes
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request(): #enter email to request password request
  if current_user.is_authenticated: #to make sure users are logged out before they reset their password
    return redirect(url_for('main.home'))
  form = RequestResetForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first() #grab the user with the email
    send_reset_email(user)
    flash('An email has been sent with instructions to reset your password.', 'info')
    return redirect(url_for('users.login'))
  return render_template('reset_request.html', title='Reset Password', form=form)
 
@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
  if current_user.is_authenticated: #to make sure users are logged out before they reset their password
    return redirect(url_for('main.home'))
  user = User.verify_reset_token(token)
  if not user: #if the token the user entered was invalid/expired
    flash('That is an invalid or expired token', 'warning')
    return redirect(url_for('users.reset_request'))
  form = ResetPasswordForm()
  if form.validate_on_submit():
    #hash the pw
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    user.password = hashed_password
    #add and commit
    db.session.commit()

    flash(f'Your password has been updated! You are now able to log in', 'success')
    return redirect(url_for('users.login')) #redirect to login page
  return render_template('reset_token.html', title='Reset Password', form=form)

makewiki/templates/about.html
{% extends "base.html"%}
{% block content%}
  <h1>About page</h1>
{% endblock content %}

makewiki/templates/account.html
{% extends "base.html"%}
{% block content%}
  <h1>{{ current_user.username }}</h1>
{% endblock content %}

makewiki/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">
  {% if title %}
  <title>Make Wiki - {{ title }}</title>
  {% else %}
  <title>Make Wiki</title>
  {% endif %}
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Makewiki</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages%}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </main>
  

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

makewiki/templates/create_post.html
{% extends "base.html"%}
{% block content%}
  <div class="content-section">
    <form method="POST" action="">
      <!-- hidden tag for csrf -->
      {{ form.hidden_tag() }} 
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ legend }}</legend>
        <div class="form-group">
          {{ form.title.label(class="form-control-label")}}
          {% if form.title.errors %}
            {{ form.title(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.title.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
              {{ form.title(class="form-control form-control-lg")}}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.content.label(class="form-control-label")}}
          {% if form.content.errors %}
            {{ form.content(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.content.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
              {{ form.content(class="form-control form-control-lg")}}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
{% endblock content %}

makewiki/templates/home.html
{% extends "base.html"%}
{% block content%}
  {% for post in posts%}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="#">{{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
  {% endfor %}
{% endblock content %}

makewiki/templates/login.html
{% extends "base.html"%}
{% block content%}
<div class="content-section">
  <form method="POST" action="">
    <!-- hidden tag for csrf -->
    {{ form.hidden_tag() }} 
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Log In</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
          {{ form.email(class="form-control form-control-lg is-invalid")}}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.email(class="form-control form-control-lg")}}
        {% endif %}
      </div>

      <div class="form-group">
        {{ form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
          {{ form.password(class="form-control form-control-lg is-invalid")}}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.password(class="form-control form-control-lg")}}
        {% endif %}
      </div>
      <div class="form-check">
        {{ form.remember(class="form-check-input")}}
        {{ form.remember.label(class="form-check-label")}}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
      <small class="text-muted ml-2">
        <a href="{{ url_for('users.reset_request') }}"> Forgot Password?</a>
      </small>
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class='text-muted'>
    Need An Account? <a class="ml-2" href="{{ url_for('users.register')}}"> Sign Up Now</a>
  </small>
</div>
{% endblock content %}

makewiki/templates/post.html
{% extends "base.html"%}
{% block content%}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post', post_id=post.id)}}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id)}}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

makewiki/templates/register.html
{% extends "base.html"%}
{% block content%}
<div class="content-section">
  <form method="POST" action="">
    <!-- hidden tag for csrf -->
    {{ form.hidden_tag() }} 
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Join Today</legend>
      <div class="form-group">
        {{ form.username.label(class="form-control-label")}}
        {% if form.username.errors %}
          {{ form.username(class="form-control form-control-lg is-invalid")}}
          <div class="invalid-feedback">
            {% for error in form.username.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.username(class="form-control form-control-lg")}}
        {% endif %}
        
      </div>
      
      <div class="form-group">
        {{ form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
          {{ form.email(class="form-control form-control-lg is-invalid")}}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.email(class="form-control form-control-lg")}}
        {% endif %}
      </div>

      <div class="form-group">
        {{ form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
          {{ form.password(class="form-control form-control-lg is-invalid")}}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.password(class="form-control form-control-lg")}}
        {% endif %}
      </div>
      
      <div class="form-group">
        {{ form.confirm_password.label(class="form-control-label")}}
        {% if form.confirm_password.errors %}
          {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
          <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.confirm_password(class="form-control form-control-lg")}}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class='text-muted'>
    Already Have An Account? <a class="ml-2" href="{{ url_for('users.login')}}"> Sign In </a>
  </small>
</div>
{% endblock content %}

makewiki/templates/reset_request.html
{% extends "base.html"%}
{% block content%}
<div class="content-section">
  <form method="POST" action="">
    <!-- hidden tag for csrf -->
    {{ form.hidden_tag() }} 
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
          {{ form.email(class="form-control form-control-lg is-invalid")}}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.email(class="form-control form-control-lg")}}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

makewiki/templates/reset_token.html
{% extends "base.html"%}
{% block content%}
<div class="content-section">
  <form method="POST" action="">
    <!-- hidden tag for csrf -->
    {{ form.hidden_tag() }} 
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</legend>
      <div class="form-group">
        {{ form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
          {{ form.password(class="form-control form-control-lg is-invalid")}}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.password(class="form-control form-control-lg")}}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.confirm_password.label(class="form-control-label")}}
        {% if form.confirm_password.errors %}
          {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
          <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.confirm_password(class="form-control form-control-lg")}}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}